/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : bigint,
  'status' : Type,
  'title' : string,
  'submitterName' : string,
  'submitterRole' : Type__3,
  'assignedTo' : [] | [string],
  'createdAt' : bigint,
  'submittedBy' : Principal,
  'description' : string,
  'updatedAt' : bigint,
  'category' : Type__1,
  'priority' : Type__2,
  'adminResponse' : [] | [string],
}
export interface ComplaintStats {
  'resolved' : bigint,
  'closed' : bigint,
  'total' : bigint,
  'open' : bigint,
  'inProgress' : bigint,
}
export interface SubmitComplaintRequest {
  'title' : string,
  'submitterName' : string,
  'submitterRole' : Type__3,
  'description' : string,
  'category' : Type__1,
  'priority' : Type__2,
}
export type Type = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type Type__1 = { 'itTechnical' : null } |
  { 'other' : null } |
  { 'administrative' : null } |
  { 'academic' : null } |
  { 'hostelCanteen' : null } |
  { 'infrastructure' : null } |
  { 'facultyConduct' : null };
export type Type__2 = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export type Type__3 = { 'admin' : null } |
  { 'staff' : null } |
  { 'student' : null };
export interface UpdateStatusRequest {
  'id' : bigint,
  'assignedTo' : [] | [string],
  'newStatus' : Type,
  'adminResponse' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaintById' : ActorMethod<[bigint], [] | [Complaint]>,
  'getComplaintStats' : ActorMethod<[], ComplaintStats>,
  'getMyComplaints' : ActorMethod<[], Array<Complaint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitComplaint' : ActorMethod<[SubmitComplaintRequest], bigint>,
  'updateComplaintStatus' : ActorMethod<[UpdateStatusRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];