/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Type__3 = IDL.Variant({
  'admin' : IDL.Null,
  'staff' : IDL.Null,
  'student' : IDL.Null,
});
export const Type__1 = IDL.Variant({
  'itTechnical' : IDL.Null,
  'other' : IDL.Null,
  'administrative' : IDL.Null,
  'academic' : IDL.Null,
  'hostelCanteen' : IDL.Null,
  'infrastructure' : IDL.Null,
  'facultyConduct' : IDL.Null,
});
export const Type__2 = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : Type,
  'title' : IDL.Text,
  'submitterName' : IDL.Text,
  'submitterRole' : Type__3,
  'assignedTo' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : Type__1,
  'priority' : Type__2,
  'adminResponse' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ComplaintStats = IDL.Record({
  'resolved' : IDL.Nat,
  'closed' : IDL.Nat,
  'total' : IDL.Nat,
  'open' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const SubmitComplaintRequest = IDL.Record({
  'title' : IDL.Text,
  'submitterName' : IDL.Text,
  'submitterRole' : Type__3,
  'description' : IDL.Text,
  'category' : Type__1,
  'priority' : Type__2,
});
export const UpdateStatusRequest = IDL.Record({
  'id' : IDL.Nat,
  'assignedTo' : IDL.Opt(IDL.Text),
  'newStatus' : Type,
  'adminResponse' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaintById' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
  'getComplaintStats' : IDL.Func([], [ComplaintStats], ['query']),
  'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitComplaint' : IDL.Func([SubmitComplaintRequest], [IDL.Nat], []),
  'updateComplaintStatus' : IDL.Func([UpdateStatusRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Type__3 = IDL.Variant({
    'admin' : IDL.Null,
    'staff' : IDL.Null,
    'student' : IDL.Null,
  });
  const Type__1 = IDL.Variant({
    'itTechnical' : IDL.Null,
    'other' : IDL.Null,
    'administrative' : IDL.Null,
    'academic' : IDL.Null,
    'hostelCanteen' : IDL.Null,
    'infrastructure' : IDL.Null,
    'facultyConduct' : IDL.Null,
  });
  const Type__2 = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : Type,
    'title' : IDL.Text,
    'submitterName' : IDL.Text,
    'submitterRole' : Type__3,
    'assignedTo' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : Type__1,
    'priority' : Type__2,
    'adminResponse' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ComplaintStats = IDL.Record({
    'resolved' : IDL.Nat,
    'closed' : IDL.Nat,
    'total' : IDL.Nat,
    'open' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const SubmitComplaintRequest = IDL.Record({
    'title' : IDL.Text,
    'submitterName' : IDL.Text,
    'submitterRole' : Type__3,
    'description' : IDL.Text,
    'category' : Type__1,
    'priority' : Type__2,
  });
  const UpdateStatusRequest = IDL.Record({
    'id' : IDL.Nat,
    'assignedTo' : IDL.Opt(IDL.Text),
    'newStatus' : Type,
    'adminResponse' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaintById' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
    'getComplaintStats' : IDL.Func([], [ComplaintStats], ['query']),
    'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitComplaint' : IDL.Func([SubmitComplaintRequest], [IDL.Nat], []),
    'updateComplaintStatus' : IDL.Func([UpdateStatusRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };