/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : bigint,
  'status' : Type,
  'title' : string,
  'submitterName' : string,
  'submitterType' : Type__1,
  'referenceNumber' : string,
  'assignedTo' : [] | [string],
  'createdAt' : bigint,
  'submittedBy' : Principal,
  'description' : string,
  'updatedAt' : bigint,
  'category' : Type__2,
  'submittedByUserId' : string,
  'priority' : Type__3,
  'adminResponse' : [] | [string],
}
export interface ComplaintStats {
  'resolved' : bigint,
  'closed' : bigint,
  'total' : bigint,
  'open' : bigint,
  'inProgress' : bigint,
}
export type Result = { 'ok' : {} } |
  {
    'err' : { 'alreadyExists' : null } |
      { 'invalidInput' : null } |
      { 'notFound' : null } |
      { 'internalError' : null } |
      { 'unauthorized' : null }
  };
export type Result_1 = { 'ok' : string } |
  {
    'err' : { 'alreadyExists' : null } |
      { 'invalidInput' : null } |
      { 'notFound' : null } |
      { 'internalError' : null } |
      { 'unauthorized' : null }
  };
export type Result_2 = { 'ok' : null } |
  {
    'err' : { 'alreadyExists' : null } |
      { 'invalidInput' : null } |
      { 'notFound' : null } |
      { 'internalError' : null } |
      { 'unauthorized' : null }
  };
export type Result_3 = { 'ok' : Array<Complaint> } |
  {
    'err' : { 'alreadyExists' : null } |
      { 'invalidInput' : null } |
      { 'notFound' : null } |
      { 'internalError' : null } |
      { 'unauthorized' : null }
  };
export type Result_4 = { 'ok' : bigint } |
  {
    'err' : { 'alreadyExists' : null } |
      { 'invalidInput' : null } |
      { 'notFound' : null } |
      { 'internalError' : null } |
      { 'unauthorized' : null }
  };
export type Result_5 = { 'ok' : ComplaintStats } |
  {
    'err' : { 'alreadyExists' : null } |
      { 'invalidInput' : null } |
      { 'notFound' : null } |
      { 'internalError' : null } |
      { 'unauthorized' : null }
  };
export type Result_6 = { 'ok' : Complaint } |
  {
    'err' : { 'alreadyExists' : null } |
      { 'invalidInput' : null } |
      { 'notFound' : null } |
      { 'internalError' : null } |
      { 'unauthorized' : null }
  };
export type Type = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type Type__1 = { 'admin' : null } |
  { 'staff' : null } |
  { 'student' : null };
export type Type__2 = { 'itTechnical' : null } |
  { 'other' : null } |
  { 'administrative' : null } |
  { 'academic' : null } |
  { 'hostelCanteen' : null } |
  { 'infrastructure' : null } |
  { 'facultyConduct' : null };
export type Type__3 = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export interface UserProfile {
  'userId' : string,
  'name' : string,
  'role' : Type__1,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllComplaints' : ActorMethod<[], Result_3>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaintById' : ActorMethod<[bigint], Result_6>,
  'getComplaintStats' : ActorMethod<[], Result_5>,
  'getComplaintsByUserId' : ActorMethod<[string, string], Result_3>,
  'getMyComplaintCount' : ActorMethod<[], Result_4>,
  'getMyComplaints' : ActorMethod<[], Result_3>,
  'getUserInfo' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByUserId' : ActorMethod<[string], [] | [UserProfile]>,
  'hasPasswordSet' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFirstTimeUser' : ActorMethod<[string], boolean>,
  'registerUser' : ActorMethod<[string, string, Type__1], Result_1>,
  'registerUserPublic' : ActorMethod<
    [string, string, string, Type__1],
    Result_1
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserPassword' : ActorMethod<[string, string], Result_2>,
  'submitComplaint' : ActorMethod<
    [string, Type__1, Type__2, string, string, Type__3],
    Result_1
  >,
  'submitComplaintPublic' : ActorMethod<
    [string, string, string, Type__1, Type__2, string, string, Type__3],
    Result_1
  >,
  'updateComplaintStatus' : ActorMethod<
    [bigint, Type, [] | [string], [] | [string]],
    Result
  >,
  'verifyUserPassword' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];