/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Type__1 = IDL.Variant({
  'admin' : IDL.Null,
  'staff' : IDL.Null,
  'student' : IDL.Null,
});
export const Type__2 = IDL.Variant({
  'itTechnical' : IDL.Null,
  'other' : IDL.Null,
  'administrative' : IDL.Null,
  'academic' : IDL.Null,
  'hostelCanteen' : IDL.Null,
  'infrastructure' : IDL.Null,
  'facultyConduct' : IDL.Null,
});
export const Type__3 = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : Type,
  'title' : IDL.Text,
  'submitterName' : IDL.Text,
  'submitterType' : Type__1,
  'referenceNumber' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : Type__2,
  'submittedByUserId' : IDL.Text,
  'priority' : Type__3,
  'adminResponse' : IDL.Opt(IDL.Text),
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(Complaint),
  'err' : IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'internalError' : IDL.Null,
    'unauthorized' : IDL.Null,
  }),
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : Type__1,
});
export const Result_5 = IDL.Variant({
  'ok' : Complaint,
  'err' : IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'internalError' : IDL.Null,
    'unauthorized' : IDL.Null,
  }),
});
export const ComplaintStats = IDL.Record({
  'resolved' : IDL.Nat,
  'closed' : IDL.Nat,
  'total' : IDL.Nat,
  'open' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const Result_4 = IDL.Variant({
  'ok' : ComplaintStats,
  'err' : IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'internalError' : IDL.Null,
    'unauthorized' : IDL.Null,
  }),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'internalError' : IDL.Null,
    'unauthorized' : IDL.Null,
  }),
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'internalError' : IDL.Null,
    'unauthorized' : IDL.Null,
  }),
});
export const Result = IDL.Variant({
  'ok' : IDL.Record({}),
  'err' : IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'internalError' : IDL.Null,
    'unauthorized' : IDL.Null,
  }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllComplaints' : IDL.Func([], [Result_2], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaintById' : IDL.Func([IDL.Nat], [Result_5], ['query']),
  'getComplaintStats' : IDL.Func([], [Result_4], ['query']),
  'getMyComplaintCount' : IDL.Func([], [Result_3], ['query']),
  'getMyComplaints' : IDL.Func([], [Result_2], ['query']),
  'getUserInfo' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFirstTimeUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, Type__1], [Result_1], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitComplaint' : IDL.Func(
      [IDL.Text, Type__1, Type__2, IDL.Text, IDL.Text, Type__3],
      [Result_1],
      [],
    ),
  'updateComplaintStatus' : IDL.Func(
      [IDL.Nat, Type, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Type__1 = IDL.Variant({
    'admin' : IDL.Null,
    'staff' : IDL.Null,
    'student' : IDL.Null,
  });
  const Type__2 = IDL.Variant({
    'itTechnical' : IDL.Null,
    'other' : IDL.Null,
    'administrative' : IDL.Null,
    'academic' : IDL.Null,
    'hostelCanteen' : IDL.Null,
    'infrastructure' : IDL.Null,
    'facultyConduct' : IDL.Null,
  });
  const Type__3 = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : Type,
    'title' : IDL.Text,
    'submitterName' : IDL.Text,
    'submitterType' : Type__1,
    'referenceNumber' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : Type__2,
    'submittedByUserId' : IDL.Text,
    'priority' : Type__3,
    'adminResponse' : IDL.Opt(IDL.Text),
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(Complaint),
    'err' : IDL.Variant({
      'alreadyExists' : IDL.Null,
      'invalidInput' : IDL.Null,
      'notFound' : IDL.Null,
      'internalError' : IDL.Null,
      'unauthorized' : IDL.Null,
    }),
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : Type__1,
  });
  const Result_5 = IDL.Variant({
    'ok' : Complaint,
    'err' : IDL.Variant({
      'alreadyExists' : IDL.Null,
      'invalidInput' : IDL.Null,
      'notFound' : IDL.Null,
      'internalError' : IDL.Null,
      'unauthorized' : IDL.Null,
    }),
  });
  const ComplaintStats = IDL.Record({
    'resolved' : IDL.Nat,
    'closed' : IDL.Nat,
    'total' : IDL.Nat,
    'open' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({
    'ok' : ComplaintStats,
    'err' : IDL.Variant({
      'alreadyExists' : IDL.Null,
      'invalidInput' : IDL.Null,
      'notFound' : IDL.Null,
      'internalError' : IDL.Null,
      'unauthorized' : IDL.Null,
    }),
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Nat,
    'err' : IDL.Variant({
      'alreadyExists' : IDL.Null,
      'invalidInput' : IDL.Null,
      'notFound' : IDL.Null,
      'internalError' : IDL.Null,
      'unauthorized' : IDL.Null,
    }),
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Variant({
      'alreadyExists' : IDL.Null,
      'invalidInput' : IDL.Null,
      'notFound' : IDL.Null,
      'internalError' : IDL.Null,
      'unauthorized' : IDL.Null,
    }),
  });
  const Result = IDL.Variant({
    'ok' : IDL.Record({}),
    'err' : IDL.Variant({
      'alreadyExists' : IDL.Null,
      'invalidInput' : IDL.Null,
      'notFound' : IDL.Null,
      'internalError' : IDL.Null,
      'unauthorized' : IDL.Null,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllComplaints' : IDL.Func([], [Result_2], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaintById' : IDL.Func([IDL.Nat], [Result_5], ['query']),
    'getComplaintStats' : IDL.Func([], [Result_4], ['query']),
    'getMyComplaintCount' : IDL.Func([], [Result_3], ['query']),
    'getMyComplaints' : IDL.Func([], [Result_2], ['query']),
    'getUserInfo' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFirstTimeUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, Type__1], [Result_1], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitComplaint' : IDL.Func(
        [IDL.Text, Type__1, Type__2, IDL.Text, IDL.Text, Type__3],
        [Result_1],
        [],
      ),
    'updateComplaintStatus' : IDL.Func(
        [IDL.Nat, Type, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };