/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ComplaintStats {
    resolved: bigint;
    closed: bigint;
    total: bigint;
    open: bigint;
    inProgress: bigint;
}
export interface UpdateStatusRequest {
    id: bigint;
    assignedTo?: string;
    newStatus: Type;
    adminResponse?: string;
}
export interface Complaint {
    id: bigint;
    status: Type;
    title: string;
    submitterName: string;
    submitterRole: Type__3;
    assignedTo?: string;
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    updatedAt: bigint;
    category: Type__1;
    priority: Type__2;
    adminResponse?: string;
}
export interface SubmitComplaintRequest {
    title: string;
    submitterName: string;
    submitterRole: Type__3;
    description: string;
    category: Type__1;
    priority: Type__2;
}
export interface UserProfile {
    name: string;
}
export enum Type {
    resolved = "resolved",
    closed = "closed",
    open = "open",
    inProgress = "inProgress"
}
export enum Type__1 {
    itTechnical = "itTechnical",
    other = "other",
    administrative = "administrative",
    academic = "academic",
    hostelCanteen = "hostelCanteen",
    infrastructure = "infrastructure",
    facultyConduct = "facultyConduct"
}
export enum Type__2 {
    low = "low",
    high = "high",
    urgent = "urgent",
    medium = "medium"
}
export enum Type__3 {
    admin = "admin",
    staff = "staff",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplaintById(id: bigint): Promise<Complaint | null>;
    getComplaintStats(): Promise<ComplaintStats>;
    getMyComplaints(): Promise<Array<Complaint>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitComplaint(request: SubmitComplaintRequest): Promise<bigint>;
    updateComplaintStatus(request: UpdateStatusRequest): Promise<void>;
}
import type { Complaint as _Complaint, SubmitComplaintRequest as _SubmitComplaintRequest, Type as _Type, Type__1 as _Type__1, Type__2 as _Type__2, Type__3 as _Type__3, UpdateStatusRequest as _UpdateStatusRequest, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintById(arg0: bigint): Promise<Complaint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintStats(): Promise<ComplaintStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintStats();
            return result;
        }
    }
    async getMyComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyComplaints();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyComplaints();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitComplaint(arg0: SubmitComplaintRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComplaint(to_candid_SubmitComplaintRequest_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComplaint(to_candid_SubmitComplaintRequest_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateComplaintStatus(arg0: UpdateStatusRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(to_candid_UpdateStatusRequest_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(to_candid_UpdateStatusRequest_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Complaint_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Complaint {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Type__2_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__2): Type__2 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Type__3_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__3): Type__3 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Complaint]): Complaint | null {
    return value.length === 0 ? null : from_candid_Complaint_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Type;
    title: string;
    submitterName: string;
    submitterRole: _Type__3;
    assignedTo: [] | [string];
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    updatedAt: bigint;
    category: _Type__1;
    priority: _Type__2;
    adminResponse: [] | [string];
}): {
    id: bigint;
    status: Type;
    title: string;
    submitterName: string;
    submitterRole: Type__3;
    assignedTo?: string;
    createdAt: bigint;
    submittedBy: Principal;
    description: string;
    updatedAt: bigint;
    category: Type__1;
    priority: Type__2;
    adminResponse?: string;
} {
    return {
        id: value.id,
        status: from_candid_Type_n6(_uploadFile, _downloadFile, value.status),
        title: value.title,
        submitterName: value.submitterName,
        submitterRole: from_candid_Type__3_n8(_uploadFile, _downloadFile, value.submitterRole),
        assignedTo: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.assignedTo)),
        createdAt: value.createdAt,
        submittedBy: value.submittedBy,
        description: value.description,
        updatedAt: value.updatedAt,
        category: from_candid_Type__1_n11(_uploadFile, _downloadFile, value.category),
        priority: from_candid_Type__2_n13(_uploadFile, _downloadFile, value.priority),
        adminResponse: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.adminResponse))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itTechnical: null;
} | {
    other: null;
} | {
    administrative: null;
} | {
    academic: null;
} | {
    hostelCanteen: null;
} | {
    infrastructure: null;
} | {
    facultyConduct: null;
}): Type__1 {
    return "itTechnical" in value ? Type__1.itTechnical : "other" in value ? Type__1.other : "administrative" in value ? Type__1.administrative : "academic" in value ? Type__1.academic : "hostelCanteen" in value ? Type__1.hostelCanteen : "infrastructure" in value ? Type__1.infrastructure : "facultyConduct" in value ? Type__1.facultyConduct : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
}): Type__2 {
    return "low" in value ? Type__2.low : "high" in value ? Type__2.high : "urgent" in value ? Type__2.urgent : "medium" in value ? Type__2.medium : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
}): Type {
    return "resolved" in value ? Type.resolved : "closed" in value ? Type.closed : "open" in value ? Type.open : "inProgress" in value ? Type.inProgress : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    staff: null;
} | {
    student: null;
}): Type__3 {
    return "admin" in value ? Type__3.admin : "staff" in value ? Type__3.staff : "student" in value ? Type__3.student : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Array<Complaint> {
    return value.map((x)=>from_candid_Complaint_n4(_uploadFile, _downloadFile, x));
}
function to_candid_SubmitComplaintRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitComplaintRequest): _SubmitComplaintRequest {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Type__1_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Type__2_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): _Type__2 {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Type__3_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__3): _Type__3 {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStatusRequest_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStatusRequest): _UpdateStatusRequest {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    submitterName: string;
    submitterRole: Type__3;
    description: string;
    category: Type__1;
    priority: Type__2;
}): {
    title: string;
    submitterName: string;
    submitterRole: _Type__3;
    description: string;
    category: _Type__1;
    priority: _Type__2;
} {
    return {
        title: value.title,
        submitterName: value.submitterName,
        submitterRole: to_candid_Type__3_n21(_uploadFile, _downloadFile, value.submitterRole),
        description: value.description,
        category: to_candid_Type__1_n23(_uploadFile, _downloadFile, value.category),
        priority: to_candid_Type__2_n25(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignedTo?: string;
    newStatus: Type;
    adminResponse?: string;
}): {
    id: bigint;
    assignedTo: [] | [string];
    newStatus: _Type;
    adminResponse: [] | [string];
} {
    return {
        id: value.id,
        assignedTo: value.assignedTo ? candid_some(value.assignedTo) : candid_none(),
        newStatus: to_candid_Type_n29(_uploadFile, _downloadFile, value.newStatus),
        adminResponse: value.adminResponse ? candid_some(value.adminResponse) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__3): {
    admin: null;
} | {
    staff: null;
} | {
    student: null;
} {
    return value == Type__3.admin ? {
        admin: null
    } : value == Type__3.staff ? {
        staff: null
    } : value == Type__3.student ? {
        student: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    itTechnical: null;
} | {
    other: null;
} | {
    administrative: null;
} | {
    academic: null;
} | {
    hostelCanteen: null;
} | {
    infrastructure: null;
} | {
    facultyConduct: null;
} {
    return value == Type__1.itTechnical ? {
        itTechnical: null
    } : value == Type__1.other ? {
        other: null
    } : value == Type__1.administrative ? {
        administrative: null
    } : value == Type__1.academic ? {
        academic: null
    } : value == Type__1.hostelCanteen ? {
        hostelCanteen: null
    } : value == Type__1.infrastructure ? {
        infrastructure: null
    } : value == Type__1.facultyConduct ? {
        facultyConduct: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
} {
    return value == Type__2.low ? {
        low: null
    } : value == Type__2.high ? {
        high: null
    } : value == Type__2.urgent ? {
        urgent: null
    } : value == Type__2.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == Type.resolved ? {
        resolved: null
    } : value == Type.closed ? {
        closed: null
    } : value == Type.open ? {
        open: null
    } : value == Type.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
